### ISSUE TITLE
Can the demo chat-app only be built in mac?

### ISSUE THREAD

**Issue by kpachhai** [elastos/Elastos.NET.Carrier.Nodejs.SDK#29]
I was trying to run the demo chat-app on my ubuntu VM and i ran into some issues. I think the readme should be updated to say that this can only be built on a certain platform.
Below is the error I got when I tried doing "npm i"
```bash
kpachhai@kp-ubuntu:~/repos/github.com/elastos/Elastos.NET.Carrier.Nodejs.SDK/example/chat-app$ npm install
npm WARN sass-loader@3.2.3 requires a peer of node-sass@^3.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@3.2.3 requires a peer of webpack@^1.12.6 || ^2.1.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.0 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 84 packages in 16.668s
```

As you can see, my platform is unsupported I suppose. And only darwin is supported. Or is there a way I can get this installed on my ubuntu as well? Just curious

**Comment by liyangwood** [comment]
@kpachhai 
Hi, I test on ubuntu 16.04 desktop version, looks like it could be work.
so could you provide more about your environment details. .e.g, node version, os version ...
and I did not find any error from the log above, please run with "npm start" and check is there any error output?

**Comment by kpachhai** [comment]
I have ubuntu 18.04 LTS, node version 9.10.0

Also, when I run "npm start", I get the following error:

```bash
kpachhai@kp-ubuntu:~/repos/github.com/elastos/Elastos.NET.Carrier.Nodejs.SDK/example/chat-app$ npm start

> chat-app@0.0.1 start /home/kpachhai/repos/github.com/elastos/Elastos.NET.Carrier.Nodejs.SDK/example/chat-app
> npm run dev


> chat-app@0.0.1 dev /home/kpachhai/repos/github.com/elastos/Elastos.NET.Carrier.Nodejs.SDK/example/chat-app
> node build/dev_build.js && npm run nw

Hash: c89337389eaf16b09b6c
Version: webpack 3.11.0
Time: 8715ms
                                 Asset       Size  Chunks                    Chunk Names
static/fonts/element-icons.6f0a763.ttf      11 kB          [emitted]         
                      static/js/app.js    1.57 MB       0  [emitted]  [big]  app
                   static/js/vendor.js    7.82 MB       1  [emitted]  [big]  vendor
                            index.html  467 bytes          [emitted]         
                      Carrier/index.js    9.16 kB          [emitted]         

ERROR in ./src/router/index.js
Module not found: Error: Can't resolve '@/layout/Setting' in '/home/kpachhai/repos/github.com/elastos/Elastos.NET.Carrier.Nodejs.SDK/example/chat-app/src/router'
 @ ./src/router/index.js 5:0-39
 @ ./src/main.js

  Build failed with errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chat-app@0.0.1 dev: `node build/dev_build.js && npm run nw`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chat-app@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kpachhai/.npm/_logs/2018-05-02T10_28_07_939Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chat-app@0.0.1 start: `npm run dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chat-app@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kpachhai/.npm/_logs/2018-05-02T10_28_07_960Z-debug.log
```

And when I check the logs at /home/kpachhai/.npm/_logs/2018-05-02T10_28_07_960Z-debug.log, it says the following:
```
kpachhai@kp-ubuntu:~/repos/github.com/elastos/Elastos.NET.Carrier.Nodejs.SDK/example/chat-app$ cat /home/kpachhai/.npm/_logs/2018-05-02T10_28_07_960Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v9.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle chat-app@0.0.1~prestart: chat-app@0.0.1
6 info lifecycle chat-app@0.0.1~start: chat-app@0.0.1
7 verbose lifecycle chat-app@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle chat-app@0.0.1~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/kpachhai/repos/github.com/elastos/Elastos.NET.Carrier.Nodejs.SDK/example/chat-app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle chat-app@0.0.1~start: CWD: /home/kpachhai/repos/github.com/elastos/Elastos.NET.Carrier.Nodejs.SDK/example/chat-app
10 silly lifecycle chat-app@0.0.1~start: Args: [ '-c', 'npm run dev' ]
11 silly lifecycle chat-app@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle chat-app@0.0.1~start: Failed to exec start script
13 verbose stack Error: chat-app@0.0.1 start: `npm run dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid chat-app@0.0.1
15 verbose cwd /home/kpachhai/repos/github.com/elastos/Elastos.NET.Carrier.Nodejs.SDK/example/chat-app
16 verbose Linux 4.15.0-20-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v9.10.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error chat-app@0.0.1 start: `npm run dev`
22 error Exit status 1
23 error Failed at the chat-app@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by liyangwood** [comment]
yeah, that is typo error, please pull the latest code to test again, thanks.

**Comment by kpachhai** [comment]
Pulled the latest code and reran. Looks to be working successfully now. Thanks.
