### ISSUE TITLE
../src/elca.h:35:10: fatal error: 'ela_carrier.h' file not found. Have you checked in all code, or any ENV settings wrong?

### ISSUE THREAD

**Issue by kevingzhang** [elastos/Elastos.NET.Carrier.Nodejs.SDK#5]
Kevins-MacBook-Pro:Elastos.NET.Carrier.Nodejs.SDK kevinzhang$ node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.11.0 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/elca/src/elca.o
In file included from ../src/elca.cc:24:
../src/elca.h:35:10: fatal error: 'ela_carrier.h' file not found
#include <ela_carrier.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/elca/src/elca.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/lib/node_modules/node/bin/node" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd /Users/kevinzhang/github/Elastos.NET.Carrier.Nodejs.SDK
gyp ERR! node -v v9.11.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by kevingzhang** [comment]
I may be caused by a failure build of NativeSDK.

**Comment by kevingzhang** [comment]
My current env is 
 echo $CARRIER_NATIVE_SDK
/Users/kevinzhang/github/Elastos.NET.Carrier.Native.SDK/build/_dist/Linux-x86_64/debug
and I can find the file here
ls ela_carrier.h
ela_carrier.h
Kevins-MacBook-Pro:include kevinzhang$ pwd
/Users/kevinzhang/github/Elastos.NET.Carrier.Native.SDK/build/_dist/Linux-x86_64/debug/include

I think it is caused by some env settings. The compiler did not go to that folder to find ela_carrier.h

**Comment by kuit** [comment]
Before, I user relative path to set CARRIER_NATIVE_SDK. 
Now change to absolute path, and if $(CARRIER_NATIVE_SDK) is a relative path, please modify binding.gyp :
"-L<!(echo $CARRIER_NATIVE_SDK)/lib" ==> "-L<(module_root_dir)/<!(echo $CARRIER_NATIVE_SDK)/lib"

**Comment by kevingzhang** [comment]
I am using absolute path, see this
echo $CARRIER_NATIVE_SDK
/Users/kevinzhang/github/Elastos.NET.Carrier.Native.SDK/build/_dist/Linux-x86_64/debug
So what should I modify? You just mentioned if it is relative path then modify binding.gyp. How about my case? @kuit

**Comment by kuit** [comment]
I have uploaded binding.gyp and readme.MD two hour ago, the defaulte value is absolute path setting. You can use your path to build. @kevingzhang

**Comment by kevingzhang** [comment]
Still  not working. This is my terminal output
Kevins-MacBook-Pro:Elastos.NET.Carrier.Nodejs.SDK kevinzhang$ export CARRIER_NATIVE_SDK=$/Users/kevinzhang/github/Elastos.NET.Carrier.Native.SDK/build/_dist/Linux-x86_64/debug
Kevins-MacBook-Pro:Elastos.NET.Carrier.Nodejs.SDK kevinzhang$ node-gyp buildgyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.11.0 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/elca/src/elca.o
In file included from ../src/elca.cc:24:
../src/elca.h:35:10: fatal error: 'ela_carrier.h' file not found
#include <ela_carrier.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/elca/src/elca.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/lib/node_modules/node/bin/node" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd /Users/kevinzhang/github/Elastos.NET.Carrier.Nodejs.SDK
gyp ERR! node -v v9.11.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by kevingzhang** [comment]
Oh, I see, I am running on Mac. but that path is for Linux.

**Comment by kevingzhang** [comment]
Do you have a build instruction for Mac, or can you build a docker to try?
