### ISSUE TITLE
Error running demo.js

### ISSUE THREAD

**Issue by kpachhai** [elastos/Elastos.NET.Carrier.Nodejs.SDK#6]
I was able to get everything built nicely and also installed node v9.10.0 but when i tried to run the demo, i ran into some issues. See below:

```
kpachhai@kpubuntu:~/repos/github.com/elastos/Elastos.NET.Carrier.Nodejs.SDK$ node ./example/demo/demo.js
module.js:545
    throw err;
    ^

Error: Cannot find module '../../build/Debug/elca'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/kpachhai/repos/github.com/elastos/Elastos.NET.Carrier.Nodejs.SDK/example/demo/demo.js:25:20)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

**Comment by kevingzhang** [comment]
Did you get any build error when compiling the SDK? It looks like the building of SDK failed.

**Comment by kpachhai** [comment]
It looks like there may be some path related errors for sure because if I copy contents from Release directory and put it in Debug like so:
```
cp -r build/Release build/Debug
```

And then run the following again, I am able to build it successfully.
```
$ node ./example/demo/demo.js
elacarrier-5.0.1
index:0-- ipv4:13.58.208.50, ipv6:(null), port:33445, public_key:89vny8MrKdDKs7Uta9RdVmspPjnRMdwMmaiEW27pZ7gh
index:1-- ipv4:18.216.102.47, ipv6:(null), port:33445, public_key:G5z8MqiNDFTadFUPfMdYsYtkUDbX5mNCMVHMZtsCnFeb
index:2-- ipv4:18.216.6.197, ipv6:(null), port:33445, public_key:H8sqhRrQuJZ6iLtP2wanxt4LzdNrN2NNFnpPdq1uJ9n2
index:3-- ipv4:54.223.36.193, ipv6:(null), port:33445, public_key:5tuHgK1Q4CYf4K5PutsEPK5E3Z7cbtEBdx7LwmdzqXHL
index:4-- ipv4:52.80.187.125, ipv6:(null), port:33445, public_key:3khtxZo89SBScAMaHhTvD68pPHiKxgZT6hTCSZZVgNEm
2018-04-09 23:28:19 - INFO    : Carrier: Carrier node created.
(node:14181) Warning: N-API is an experimental feature and could change at any time.

Friends list from carrier network:
  ID                                              Connection   Label
  ----------------                                ----------   -----
  ----------------
Total 0 friends.
Command:$
Connected to carrier network.
Command:$
```

**Comment by kevingzhang** [comment]
Hi @kuit  please handle this issue. If no longer valid, please close it. 
You need to do some clean up work
